controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

home:
  path: /
  controller: App\Controller\HomeController::home

app_login:
  path: /login
  controller: App\Controller\LoginController::login

_logout_main:
  path: /logout
  controller: App\Controller\LoginController::logout

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

reset_password:
  path: /resetPassword
  controller: src\Controller\ResetPasswordController::createResetPasswordRequest

app_trick_new:
  path: /newTrick
  controller: App\Controller\TrickController::new

app_trick_show:
  path: /show/{slug}
  # path: /{id}/show
  controller: App\Controller\TrickController::show

app_trick_edit:
  path: /edit/{slug}
  # path: /{id}/show
  controller: App\Controller\TrickController::edit

app_trick_delete:
  path: /trick/{slug}/delete
  controller: App\Controller\TrickController::delete
